"""Initial migration

Revision ID: 13ccb49ecaed
Revises: 
Create Date: 2025-08-17 05:23:26.639162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ccb49ecaed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.create_index('ix_user_username', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_index('ix_user_email')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('online')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('room')

    # ### end Alembic commands ###
